language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g npm
  - npm install -g karma-cli
before_script:
  - npm install karma-sauce-launcher
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
  - "karma start karma.conf-sauce.js"
notifications:
  email: false
env:
  matrix: SAUCE_USERNAME=backbonejs SAUCE_ACCESS_KEY=23af9fb4-f413-42a1-aaec-d22bcaff7ad4